- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1362
https://tools.hmcts.net/jira/browse/SIDM-1359
Update API Spec
```
[ ] Yes
[x] No
```
> Update API-Spec version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1375
Incremented spec and bom versions.
https://github.com/hmcts/idam-api-spec/pull/10 have to be merged before this one.
```
[ ] Yes
[ ] No
```
> SIDM-1375 incremented idam-api-spec and bom versions,

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1361
Updated API-Spec version
Depends on: https://github.com/hmcts/idam-api-spec/pull/11
```
[y] Yes
[ ] No
```
> SIDM-1361: Update API-Spec version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1375
incremented idam-api-spec and bom versions.
https://github.com/hmcts/idam-api-spec/pull/12 have to be merged before this one.
```
[ ] Yes
[ ] No
```
> SIDM-1375 incremented idam-api-spec and bom versions.

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1309
* Changed version of Application Insights
* Added a dependency to spring-boot-starter for Application Insights
```
[ ] Yes
[x] No
```
> SIDM-1309: Application Insights

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1561
Incremented idam-api-spec and bom versions. 
https://github.com/hmcts/idam-api-spec/pull/13 has to be merged before this one
```
[ ] Yes
[X] No
```
> SIDM-1561 incremented idam-api-spec and bom versions.

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1563
Bump api-spec version
Related PR: https://github.com/hmcts/idam-api-spec/pull/16
```
[ ] Yes
[x] No
```
> SIDM-1563: Bump api-spec version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1427
Added dependencies for using Feign
```
[ ] Yes
[ ] No
```
> added Feign dependencies

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1266
Use latest idam-api-spec
```
[ ] Yes
[x] No
```
> SIDM-1266 Use latest idam-api-spec

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1643
Add dependencies for app insights logging
```
[ ] Yes
[ ] No
```
> add app insights logging dependencies

- pom.xml
Upgrade to idam-api-spec version that includes a testing support endpoint for adding/removing redirect URIs to/from services.
```
[ ] Yes
[x] No
```
> Update idam-api-spec version.

- pom.xml
Update Spring Boot version to address vulnerability (CVE-2018-11039, CVE-2018-11040)
```
[ ] Yes
[x] No
```
> Updated Spring Boot version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1971
Use idam-api-spec 2.5.2
```
[ ] Yes
[x] No
```
> SIDM-1971 Implement OAuth2 client_credentials API

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1972
```
[ ] Yes
[x] No
```
> SIDM-1972 Updated idam-api-spec version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1848
Upgrading idam-api-spec to the version that contains the dynamic role assignment API specification.
```
[ ] Yes
[x] No
```
> Upgrade to idam-api-spec 2.6.0

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-1847  (blank names)
Specify minimum size for first and last names
```
[ ] Yes
[x] No
```
> Specify minimum size for first and last names

- pom.xml
Updated Jackson version to fix vulnerabilities
```
[ ] Yes
[x] No
```
> Updated jackson-databind to latest version

- pom.xml
> Update Spring version to fix vulnerabilities

- pom.xml
> SIDM-2224 Use latest idam-spec

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2224
```
[ ] Yes
[x] No
```
> Use idam-api-spec 2.6.3

- pom.xml
> [PREVIEW] SIDM-1988 updated the spec version

- pom.xml
> SIDM-2208 Upped api-spec to 2.6.6 and bom version to 1.4.8

- pom.xml
> SIDM-2308 Updating idam.api-spec.version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2202
Changing version of api-spec and increasing idam-bom version
```
[ ] Yes
[ x ] No
```
> SIDM-2022 Updating idam.api-spec.version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2202
```
[ ] Yes
[ x ] No
```
> SIDM-2202 - increased version for new API spec 

- pom.xml
> SIDM-2236 Use Spring Boot 2

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2432
increased version of API spec to 2.8.0
```
[ x ] Yes
[ ] No
```
> SIDM-2432 increased version of API spec to 2.8.0

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2205
increased API SPEC version
```
[ ] Yes
[ x ] No
```
> SIDM-2205 - increased API SPEC version

- pom.xml
> Adding dependencies for the new generated feign client

- pom.xml
> Feign client dependencies

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2592
increased API spec version
```
[ ] Yes
[ x ] No
```
> [PREVIEW] SIDM-2592 - increased API spec version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2589
increased BOM version to include the new API Spec
```
[ ] Yes
[ x ] No
```
> [PREVIEW] SIDM-2589 - increased BOM version to include the new API Spec

- pom.xml
> SIDM-1427 upping spec version

- pom.xml
> SIDM-1427 last bom update for initial oidc endpoints

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2668
Upgrading BOM to upgrade jackson library to 2.9.9
```
[ ] Yes
[ x ] No
```
> SIDM-2668 - upgrading version of Jackson libraries to 2.9.9

- pom.xml
This is for the adding refresh_token to /o/token change
```
[ ] Yes
[X] No
```
> SIDM-2662 adding new versions of spec and forgerock client

- pom.xml
This is for the last changes for OIDC, storing the cookie and new method of login
```
[X] Yes
[ ] No
```
> SIDM-2661 Upping dependency versions

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2682
upping dependencies versions
```
[ ] Yes
[ x ] No
```
> SIDM-2682 - upping dependencies versions

- pom.xml
Upping spring boot version and adding zuul as a managed dependency
```
[ ] Yes
[X] No
```
> [PREVIEW] SIDM-2727 Adding a new dependency and upping spring boot

- pom.xml
Dependencies are out of date
```
[ ] Yes
[X] No
```
> SIDM-2727 Azure AI Needs an update

- pom.xml
New dependencies for the search api
```
[ ] Yes
[X] No
```
> SIDM-2644 New spec and Forgerock Client

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2780
upping Api spec version
```
[ ] Yes
[x ] No
```
> upping Api spec version

- pom.xml
Dependencies needed for Lombok Upgrade
> SIDM-1911 Lombok and Gradle Upgrade

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2717
increasing API spec version (change to add linkedRoles)
```
[ ] Yes
[ x ] No
```
> increasing API spec version (change to add linkedRoles)

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2647
Update api-spec to include new testing endpoint
```
[ ] Yes
[x] No
```
> feat(SIDM-2647-purge): update idam-bom to include latest api-spec 2.11.0

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2530
- bump version patch
- update idam-api-spec to latest (2.11.1) to include UpdateRole changes
> SIDM-2530-linked-web update idam-api-spec to latest 2.11.1

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2531
- update bom to use latest version of forgerock http client v1.5.4 https://github.com/hmcts/idam-forgerock-http-client/releases/tag/v1.5.4
- update this version to v1.5.25
```
[ ] Yes
[x] No
```
> SIDM-2531 assign linked

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2954
Add cache refresh to idam-api-spec testing support
> SIDM-2954 cache refresh

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3002
SIDM-3002 update idam-api-spec method to take a list of test data to delete and also a test prefix if needed. And delete the data in the correct order, removing this logic from tests.
SIDM-3002 update idam-api-spec delete test-data:
Add args:
- userNames, roleNames, serviceNames, async
Add return model:
- deleted data
```
[ ] Yes
[x] No
```
> SIDM-3002 update idam-api-spec version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3096
Updated forgerock http client
> SIDM-3096 update forgerock http client

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3097
Add Caffeine, guava and serenity versions
> add caffeine and specify guava

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3153
- update http-spec
- update forgerock-cli
- bump version
```
[ ] Yes
[x] No
```
> SIDM-3153 v1.6.0 using new api-spec and forgerock-client

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3147
- api-spec 2.14.2
- fg-cli 1.7.1
```
[ ] Yes
[x] No
```
> SIDM-3147-pol-create: v1.6.1 with api-spec 2.14.2 and fg-cli 1.7.1

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3147
- v1.6.2 with api-spec 2.14.3 and fg-cli 1.7.2
```
[ ] Yes
[x] No
```
> SIDM-3147): v1.6.2 with api-spec 2.14.3 and fg-cli 1.7.2

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3147
- fr spec was wrong and ambiguous we had to re-spec some properties into maps
```
[ ] Yes
[x] No
```
> SIDM-3147: v1.6.3 with api-spec 2.14.4 and fg-cli 1.7.3 :package:

- pom.xml
Upgrade the api spec.
```
[ ] Yes
[x] No
```
> SIDM-2856 Upgrade api spec.

- pom.xml
Update jackson-databind to 2.10 and nimbus-jose-jwt to 8.1
```
[ ] Yes
[x] No
```
> refactor(nimbus and databind): update dependencies to latest

- README.md
- pom.xml
Set jackson to 2.9.9 again as 2.10 bom does not exist
```
[ ] Yes
[x] No
```
> revert(databind): set to 2.9.9 again as 2.10 bom does not exist

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3293
- update http-spec and http-cli
```
[ ] Yes
[x] No
```
> feat(SIDM-3293-otp-bom): v1.70 with new api-spec and http-client

- pom.xml
Upgrade forgerock.http.client.version.
```
[x] Yes
[ ] No
```
> Upgrade forgerock.http.client.version.

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3324
bump version to 1.8.0
use api-spec to 2.16.0
use http-cli to 1.9.0
```
[ ] Yes
[x] No
```
> feat(SIDM-3324-get-pols): v1.8.0: api-spec v2.16.0, http-cli v1.9.0

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3248
fix too many otp attempts
```
[ ] Yes
[x] No
```
> feat(SIDM-3248-val4): v1.9.0 otp: add support for too many attempts

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-2040
- update api-spec to 2.17.1
General:
- blacklisted: Your password is too easy to guess
- containing personal info: Do not include your name or email in your password
- did not match rules: Your password didn't have all the required characters
```
[ ] Yes
[x] No
```
before | after
--- | ---
> feat(SIDM-2040-pw): v1.9.1 update api-spec to 2.17.1

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3441
v1.9.2: bump api-spec to v2.17.2
```
[ ] Yes
[x] No
```
> feat(SIDM-3441-spec): v1.9.2: bump api-spec to v2.17.2

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3397
```
[x] Yes
[ ] No
```
> SIDM-3397 Upgrade api-spec.

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-3100
Fix Json Web Key Set schema as per correct schema https://auth0.com/docs/tokens/reference/jwt/jwks-properties
Which is causing trouble in sandbox
Context:
In order to be able to login into Sandbox via web-admin
We had to fix this Json Web Key Set schema which was always wrong
```
[ ] Yes
[x] No
```
> feat(sidm-3100-jwk): v1.9.5: spec:v2.17.5, cli:v1.9.1

- pom.xml
> bump version forgerock.http.client to 2.0.0

- .travis.yml
- build.gradle
Attempt to fix bintray upload.
```
[ ] Yes
[x] No
```
> Change publications config and add --info.

- build.gradle
> Fix uploading.

- pom.xml
> bump version 2.0.1

- build.gradle
- pom.xml
Upgrade some dependencies to fix CVE-2020-9488 vulnerability
```
[ ] Yes
[x] No
```
> Upgrade SpringBoot + log4j dependencies.

- pom.xml
Upgrade spring boot to 2.3.0
```
[ ] Yes
[x] No
```
> Update pom.xml v2.1.1 spring-b 2.3.0

- pom.xml
Downgrade SpringBoot as it introduces a major ElasticSearch upgrade.
Bump log4j version.
```
[ ] Yes
[x] No
```
> Preview's dependency fixes.

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-4188
```
[x] Yes
[ ] No
```
> SIDM-4188 Upgrade forgerock.http.client.version

- pom.xml
> feign upgrade to 11.0

- pom.xml
Updated api-spec needed for stale users
```
[ ] Yes
[ x] No
```
> updated bom version and api-spec version

- pom.xml
Adjust feign version to the most suitable one for us. The next versions require too much investigation. We can upgrade to those later.
```
[ ] Yes
[x] No
```
> Adjust feign version to the most suitable one

- pom.xml
- bump api-spec version
- bump fr http client version
- add feign jackson dependency for other projects
```
[ ] Yes
[x] No
```
> SIDM-4092 WIP

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-4543
updated bom and new idam-api-spec version
```
[ ] Yes
[x ] No
```
> updated bom and idam-api-spec versions

- pom.xml
Set the version to 2.3.3. Re-introduce AuthTrees changes.
```
[x] Yes
[ ] No
```
> SIDM-4092 Set the version to 2.3.3. Re-introduce AuthTrees changes.

- pom.xml
> upgrade forgerock.http.client.version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-4411
```
[ ] Yes
[ x] No
```
> SIDM-4411 

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-4832
```
[ ] Yes
[ x] No
```
> SIDM-4832: updated idam-api-spec

- pom.xml
> SIDM-4824 Bump dependencies version for the new MFA

- pom.xml
> Version-Bump

- pom.xml
Let spring-boot choose the correct nimbus-jose version
> Remove manual nimbus versioning

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-5587
Update app insight version and http client version
```
[ ] Yes
[X] No
```
> update app insight and http client versions

- pom.xml
N/A
Downgrade app insights to 2.5.1
```
[ ] Yes
[X] No
```
> downgrade app insights to 2.5.1

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-5884
Update idam-api-spec
```
[ ] Yes
[X] No
```
> update api spec version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-5943
update api-spec and forgerock-http-client
```
[ ] Yes
[X] No
```
> SIDM-5943 update api-spec and forgerock-http-client

- pom.xml
N/A
Address CVE-2021-33037.
```
[ ] Yes
[x] No
```
> Upgrade Spring Boot to latest 2.4.x version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-6016
Add refdata mock
```
[ ] Yes
[X] No
```
> SIDM-6016 update api spec for mocked refdata

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-5009
Update httpclient version
```
[ ] Yes
[X] No
```
> SIDM-5009 update httpclient version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-6914
Bump up idam-api-spec version after adding user's account locked time
```
[ ] Yes
[x] No
```
> SIDM-6914 Bump up idam-api-spec version

- pom.xml
https://tools.hmcts.net/jira/browse/SIDM-7346
Bump idam-api-spec version following changes to add user management endpoint for removing SSO from user
```
[ ] Yes
[x] No
```
> SIDM-7346 Bump idam-api-spec version

- pom.xml
[Upgrade idam-api-spec and idam-forgerock-http-client versions for PKCE](https://tools.hmcts.net/jira/browse/SIDM-7542)
Upgrade idam-api-spec and idam-forgerock-http-client versions for PKCE
```
[ ] Yes
[x] No
```
> SIDM-7542 Upgrade idam-api-spec and idam-forgerock-http-client versions for PKCE
